# Generated by Django 5.1.1 on 2024-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0002_alter_recipe_pub_date_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='instruction_order',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
