# Generated by Django 5.1.1 on 2024-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0003_remove_instruction_instruction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='instruction_order',
            field=models.IntegerField(default=0),
        ),
    ]
