# Generated by Django 5.1.1 on 2024-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0004_instruction_instruction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instruction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text',
            field=models.CharField(max_length=500),
        ),
    ]
