# Generated by Django 5.1.1 on 2024-09-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0005_ingredient_is_deleted_instruction_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_deleted',
        ),
    ]
