# Generated by Django 5.1.1 on 2024-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0006_remove_ingredient_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
