# Generated by Django 5.1.1 on 2024-11-18 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0012_rename_user_vpuser_alter_recipe_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vpuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vpuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vpuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='vpuser',
            name='username',
        ),
        migrations.AddField(
            model_name='vpuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpuser',
            name='ingredients_at_home',
            field=models.ManyToManyField(blank=True, to='voxpopulirecipes.ingredient'),
        ),
        migrations.AddField(
            model_name='vpuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
