# Generated by Django 5.1.4 on 2025-01-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0018_cuisine_recipe_avg_rating_recipe_number_of_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
