# Generated by Django 5.1.4 on 2025-01-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0019_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='baking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='baking',
            field=models.BooleanField(default=False),
        ),
    ]
