# Generated by Django 5.1.4 on 2025-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0021_alter_cookingplan_user_cookedinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date rated'),
        ),
    ]
