# Generated by Django 5.1.4 on 2025-01-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0022_rating_rating_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_ratings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_uses',
        ),
    ]
