# Generated by Django 5.1.4 on 2025-01-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxpopulirecipes', '0026_metaingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaIngredient',
        ),
    ]
